export const actionTypes = {
    //Authentication
  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",
  LOGOUT: "USERS_LOGOUT",

//PROFILE
GET_PROFILE_SUCCESS :'GET_PROFILE_SUCCESS',
GET_PROFILE_FAILURE :'GET_PROFILE_FAILURE',
UPDATE_PROFILE_SUCCESS:'UPDATE_PROFILE_SUCCESS',
UPDATE_PROFILE_FAILURE :'UPDATE_PROFILE_FAILURE',

//IPOS
GET_NSE_IPO_LIST_SUCCESS : 'GET_NSE_IPO_LIST_SUCCESS',
GET_NSE_IPO_LIST_FAILURE:'GET_NSE_IPO_LIST_FAILURE',

GET_NSE_IPO_DETAILS_SUCCESS :'GET_NSE_IPO_DETAILS',
GET_NSE_IPO_DETAILS_FAILURE :'GET_NSE_IPO_DETAILS_FAILURE'
  
}